### ISSUE TITLE
skip workgroup name

### ISSUE THREAD

**Issue by vinhdizzo** [tlh/workgroups.el#6]
I guess I'm too used to screen and escreen/elscreen.  I haven't found the use for named workgroups.  Is there a way to not have to name the workgroups when they are created?  I just refer them as 0-9.

**Comment by joelmccracken** [comment]
I use these, but maybe that's because I never really used screen.

**Comment by tlh** [comment]
There're a couple reasons I think mandatory workgroup names are a good idea.  First, they're used in a variety of displays, like the mode-line display, and the messages after commands like `wg-switch-to-workgroup`, `wg-kill-workgroup`, etc.  These displays become a lot less informative without names.  Second, since you can't persist window-configs with escreen or elscreen it makes sense not to have to name your screens, because they're ephemeral anyway. But since workgroups can be persisted, they may stick around for the entire duration of projects -- weeks, months, maybe longer.  And with the new workgroup-local buffer-list stuff, Workgroups is growing into a framework for isolating projects from one another within the same Emacs session, which makes names even more necessary.  So, I'm going require names for workgroups for the time being.

**Comment by vinhdizzo** [comment]
I see your point.

Can there be at least default group names then?  So that the user can just press enter when asked for a name and have things just work.  I believe each workgroup is associated with a number.  Can a number be the default name?

**Comment by tlh** [comment]
That's reasonable :)  I'll add it to the TODO.

**Comment by vinhdizzo** [comment]
Cool.  Can you update this thread when this feature is implemented?  I'm holding out on using workgroups on a day to day basis because of this.  Thanks so much!

**Comment by tlh** [comment]
Well, it's already in the experimental branch.  I'm reluctant to patch master, as I don't want to introduce new bugs into it while all my time is taken up elsewhere.  The new revision should be ready in about a week, though.

**Comment by vinhdizzo** [comment]
Hi.  Doesn't seem you've committed the revision to the master branch.  Can you post here once it is?  Thanks.

**Comment by tlh** [comment]
Sure.  But just so you know, when I said "new revision", I meant the big 1.0.0 version coming out soon with all the stuff that's currently in Experimental. The current Master will move to an 0.2.0 branch, and remain in its current state barring critical bug fixes, unpatched with the default workgroup name stuff.
