### ISSUE TITLE
Support dired buffers?

### ISSUE THREAD

**Issue by vinhdizzo** [tlh/workgroups.el#9]
I don't believe this is implemented.  Should it?

**Comment by tlh** [comment]
I don't know what you mean by "support".  There's `wg-dired`, which was included
to ease elscreen users' transition.  It just creates a new one window workgroup
viewing a dired buffer.

**Comment by vinhdizzo** [comment]
By support, I mean, suppose in a workgroup, a dired buffer to a location (say $HOME) is in a window, that when emacs relaunch, the dired windows persist.  Thanks!

**Comment by tlh** [comment]
Ah, I see.  No, there's currently no support for restoration of buffers that
aren't visiting files.  Here's a clip of another email explaining the situation:

"... Workgroups doesn't currently attempt to restore buffers that aren't
visiting files, mostly because it's a really hairy problem. It'll make them
visible in their correct windows if they already exist, but it won't recreate
them. Some buffers -- like Help, Info, and shell -- wouldn't be too difficult to
persist. But when you get into persisting ERC or Gnus buffers, you almost need a
dependency tree to capture everything that'd be necessary to restore them. I
will be adding a complete solution to this problem in a future version. And
there's a chance persistence of some of the simpler non-file buffer types will
be in the upcoming 1.0.0 release.

For the time being, though, the best I can offer is for you to get the workgroup
into the state you want it, with all your renamed shell buffers visible where
you want them, then `wg-update-workgroup` and `wg-save`.

Then either write a command like:

```
(defun launch-all-shells ()
  (interactive)
  (shell "foo")
  (shell "bar"))
```

Or relaunch all your shells in your .emacs

Once all your shells have been relaunched one way or another, you can
`wg-revert-workgroup`, and your workgroup will be back to its correct state ..."

**Comment by vinhdizzo** [comment]
I see.  I understand buffers like ERC and others can be very complicated.  Dired buffers should have priority compared to the others since it isn't too difficult to open those locations right?

Looking forward to more releases for worgroups.el.

**Comment by tlh** [comment]
Well, to do it right the framework has to be general enough that it can be
configured to restore any non-file-visiting buffer type, and I just haven't
gotten around to it yet.  What I don't want to do is kludge up a bunch of
special cases that have to be removed later.

**Comment by vinhdizzo** [comment]
Not sure how workgroups is implemented, but i suppose there's a filename that workgroups restore on launch.

If we store the location to the directory for each dired buffer, then it can be restored with

(dired location).

Thanks!

**Comment by tlh** [comment]
Sure.  What I'm saying is that simple though that is, I want it to be handled by
a framework that's general enough to also handle ERC buffers or Gnus buffers or
any other buffer type.  The difficulty's not in hacking up something that'll
restore Dired buffers -- that's easy.  The difficulty's in conceiving such
general framework.  Like I said, I just haven't gotten around to that yet, and I
don't want to have to rip out a bunch a special case code later.

**Comment by vinhdizzo** [comment]
Yes, I understand what you're saying.  However, I don't know whether those special buffer cases like ERC and Gnus (I don't consider dired a special case =) is do-able or even worth it as there are endless of those types.  For example, I'm a statistician, and I use ESS in emacs to access R.  How many professions are out there?  Each special buffer involves a command to call it, a working directory, etc.

The only thing I could come up that could potentially work with workgroups is for the user to write a function that starts that special buffer, and workgroup storing the name of that function.

**Comment by tlh** [comment]
That's almost exactly what I have planned -- a framework allowing users to write
their own serialization/deserialization functions for the buffer types they
need, as well as a few canned serdes functions for buffers like help, info,
shell, and dired.  Creating a framework that's robust and general enough will
require some effort, though.
